import { Button1, Button2, Button3, IconsAuthor } from "@/src/assets/import";

export const dataSetUpdates = [
  {
    icons: Button1,
    title: "Feature",
    heading: "RESPONSIVE DASHBOARD",
    headingContent: "RELEASE, APRIL 24, 2026",
    firstListText: "Seluruh halaman admin (Generator, Gallery, History, Billing, Settings, Profile, Compare) kini sepenuhnya responsif untuk mobile dan tablet.",
    secondListText: "Sidebar berubah menjadi drawer overlay dengan tombol hamburger di mobile; layout Generator menyesuaikan single-column pada layar kecil.",
    isDetail: true,
    detail: {
      headerDetail: "Mobile & Tablet Responsive Admin Dashboard",
      ContentDetail:
        "Navigasi sidebar kini tampil sebagai slide-in drawer di breakpoint < lg dengan backdrop overlay. TopBar mendapat tombol hamburger (lg:hidden). Halaman Generator mengubah layout dua kolom menjadi satu kolom di mobile, textarea prompt menyesuaikan tinggi, dan tombol Generate menjadi full-width. Semua halaman mendapat padding responsif (p-4 sm:p-6 lg:p-8). Financial ledger table mendukung horizontal scroll agar tidak overflow di layar sempit.",
      iconsContent: IconsAuthor,
      Author: "Asep Jumadi",
    },
  },
  {
    icons: Button3,
    title: "Bug Fix",
    heading: "SUSPENSE BOUNDARY",
    headingContent: "RELEASE, APRIL 24, 2026",
    firstListText: "Memperbaiki error build: useSearchParams() harus dibungkus dalam Suspense boundary di halaman /admin/generate.",
    secondListText: "GeneratorPage dipecah menjadi GeneratorContent (berisi state & useSearchParams) dan wrapper tipis Suspense untuk memenuhi persyaratan Next.js.",
    isDetail: false,
    detail: {},
  },
  {
    icons: Button1,
    title: "Feature",
    heading: "GALLERY REMIX",
    headingContent: "RELEASE, APRIL 24, 2026",
    firstListText: "Tombol Remix di halaman detail Gallery kini meneruskan prompt gambar ke halaman Generator via query parameter ?prompt=.",
    secondListText: "Generator langsung membaca dan mengisi textarea prompt dari URL sehingga proses remix berjalan tanpa perlu copy-paste manual.",
    isDetail: false,
    detail: {},
  },
  {
    icons: Button2,
    title: "Enhancement",
    heading: "TYPESCRIPT BUILD SCOPE",
    headingContent: "RELEASE, APRIL 24, 2026",
    firstListText: "Mempersempit cakupan kompilasi TypeScript: file legacy CRA (App.js, setupTests.js, reportWebVitals.js) dan direktori stitch dikecualikan dari tsconfig.",
    secondListText: "Incremental build baseline direset dengan menghapus tsconfig.tsbuildinfo yang sudah basi, mengurangi waktu kompilasi dev server secara signifikan.",
    isDetail: false,
    detail: {},
  },
  {
    icons: Button3,
    title: "Bug Fix",
    heading: "IMAGE GENERATION ENGINE",
    headingContent: "RELEASE, APRIL 24, 2026",
    firstListText: "Memperbaiki pipeline image generation: beralih dari Gemini (model deprecated) ke endpoint v1alpha Imagen 3 dengan fallback ke DALL-E 3.",
    secondListText: "Image generation kini berjalan langsung di API route tanpa queue worker, menghilangkan latensi antrian dan error timeout 504 di Vercel.",
    isDetail: true,
    detail: {
      headerDetail: "Perbaikan Total Pipeline Generasi Gambar",
      ContentDetail:
        "Rangkaian perbaikan pada engine generasi gambar: (1) Nama model Gemini exp dihapus karena sudah retired. (2) Pipeline dialihkan ke DALL-E 3. (3) Dicoba Google Imagen 3 via endpoint v1alpha. (4) Ditambahkan fallback otomatis antara Imagen dan DALL-E. Generasi kini berjalan langsung di API route sehingga lebih cepat dan tidak bergantung pada worker terpisah.",
      iconsContent: IconsAuthor,
      Author: "Asep Jumadi",
    },
  },
  {
    icons: Button3,
    title: "Bug Fix",
    heading: "REDIS & QUEUE",
    headingContent: "RELEASE, APRIL 24, 2026",
    firstListText: "Memperbaiki koneksi Upstash Redis: port diubah dari 6380 ke 6379, TLS diaktifkan, dan enableOfflineQueue dihapus untuk mencegah write failure.",
    secondListText: "Ditambahkan Redis config factory yang otomatis memilih antara koneksi lokal (ioredis) dan Upstash berdasarkan environment variable.",
    isDetail: false,
    detail: {},
  },
  {
    icons: Button3,
    title: "Bug Fix",
    heading: "CREDITS & AUTH",
    headingContent: "RELEASE, APRIL 24, 2026",
    firstListText: "Memperbaiki bug kredit FREE user yang tampil 10 alih-alih 40 — nilai default diselaraskan antara API dan skema Prisma.",
    secondListText: "Google OAuth provider kini bersifat kondisional (hanya aktif jika GOOGLE_CLIENT_ID dan GOOGLE_CLIENT_SECRET tersedia di environment).",
    isDetail: false,
    detail: {},
  },
  {
    icons: Button3,
    title: "Bug Fix",
    heading: "DEPLOYMENT & INFRA",
    headingContent: "RELEASE, APRIL 24, 2026",
    firstListText: "Memperbaiki serangkaian error deployment Vercel: konfigurasi Prisma datasource disesuaikan dengan prefix env Supabase, pgbouncer prepared statement error (code 42P05) diatasi.",
    secondListText: "Health endpoint ditingkatkan untuk mendeteksi keberadaan tabel, DATABASE_URL yang hilang, dan kompatibilitas standalone mode Vercel.",
    isDetail: false,
    detail: {},
  },
];
